### ISSUE TITLE
Composition fails

### ISSUE THREAD

**Issue by lxkain** [kylebgorman/pynini#24]
When composing two FSTs I get

```TypeError: unsupported operand type(s) for *: 'pynini.Fst' and 'pynini.Fst'```

**Comment by kylebgorman** [comment]
tl;dr use '@' instead.

Infix binary operator '*' was always a Python 2 hack, with '@', added early
in Python 3, as the ideal representation of composition, since it both
looks like LaTeX $\circ$, the standard representation of the operator in
textbooks, and is also what was used by Thrax. But Python 2.7 does not
support this operator, and this is the first version of Pynini to begin to
drop Python 2 support.

K
