### ISSUE TITLE
Example for pynini.replace

### ISSUE THREAD

**Issue by sairahul** [kylebgorman/pynini#39]
I am not sure if is the right place to ask. Could some one provide an example for pynini.replace ? The signature before 2.0.9 version looks straightforward. Its not clear how to use it now. There was an example in CHEATSHEET before 2.0.9, now it is removed and there is no example in test case as well. Is there any other function that replaces the same functionality ?

**Comment by kylebgorman** [comment]
The short answer is there aren't any good brief examples of it. It's just not very useful for grammar compilation, the point of this library, it's just in there because we try to expose all the lower-level bits just in case. (In the 150-page book we're writing on Pynini, it's not mentioned once.) Most of the things you do with it are better expressed as concatenations and unions. What do you want to use it for?

Here's something I came up with from the OpenFst docs, but as you see, an interesting example is pretty verbose and could be written much easier with pure concatenation and union.

https://gist.github.com/kylebgorman/74ae7d775392b31a1f46656915b50d1e

**Comment by sairahul** [comment]
Thanks for getting back Kyle . I am a beginner exploring the pynini. I started with your introduction paper and stuck on the replace function. The example you pointed is good enough. It's good to know that you are working on a book. Looking forward to reading it.
