### ISSUE TITLE
Possible Installation Issue

### ISSUE THREAD

**Issue by lxkain** [kylebgorman/pynini#7]
Some notes on installing pynini 2.0.0 on my system (macOS High Sierra 10.13.6)

First of all, don't forget to do a 

`$ xcode-select --install`

first. At some point during the installation process, I got:

```
In file included from src/pywrapfst.cc:594:
/usr/local/include/fst/util.h:16:10: fatal error: 'type_traits' file not found
```

Adding `"-stdlib=libc++"` to the COMPILE_ARGS allowed me to compile successfully. May this help someone else! Perhaps it could also be added to the README.rst.

**Comment by kylebgorman** [comment]
Thanks for that. I am just starting to stumble upon these issues myself.

If you want to pass `-stdlib=libc++` from the command line (rather than
adding it to `COMPILE_ARGS`) you can simply add

  CFLAGS=-stdlib=libc++ python setup.py install

(It seems like it ought to be CXXFLAGS but that doesn't seem to work.) I'm
keeping running instructions here:


http://wellformedness.com/courses/LING83600/pynini-install-instructions.html

as we find out things.

We're also trying to get it to work on the new Windows Subsystem For Linux.
This seems to be more straightforward than on Mac.

**Comment by kylebgorman** [comment]
Just checking back---did this solve the problem?

**Comment by lxkain** [comment]
Yes. I just re-installed today, using openfst 1.7.2 and pynini 2.0.7. I appreciate re2 being made unnecessary!
