### ISSUE TITLE
ImportError: libfstmpdtscript.so.25:

### ISSUE THREAD

**Issue by Oscarnibaba** [kylebgorman/pynini#75]
91/5000
How to solve this problem when importing pynini package, try to search on the Internet may be openfst dependency problem, after I manually compile and install, in its lib file also can not find libfstmpdtscript.so.25.

**Comment by kylebgorman** [comment]
Hi @Oscarnibaba, so this is a platform-specific issue (i.e., I wouldn't know how to recreate it locally) that is not under our control. (It's only partially under the control of the OpenFst installer too.) The recommended path to debug is to locate `libfstmpdtscript.so.25` on your system (for me it's in `/usr/local/lib`, but YMMV) by whatever means necessary, and then use the platform-specific mechanism to make sure the directory it is in is in your library loading path. Since there's a good chance you're on Linux, [here's the standard mechanism](https://stackoverflow.com/questions/13428910/how-to-set-the-environment-variable-ld-library-path-in-linux), but note that something different is done on MacOS, etc.

I am going to close this as #wontfix because that file is not part of the Pynini distribution.
